obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.13
inflation_radius: 0.15

#hjm add
clearing_radius: 3.0
cost_scaling_factor: 7.0
#min_obstacle_dist: 0.5

max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
